### ISSUE TITLE
Readme udpates needed

### ISSUE THREAD

**Issue by olivierbloch** [Azure-Samples/iot-hub-python-get-started#1]
Hey @dalechen 
Great to see this sample here!
Let me suggest a couple minor changes to the Readme:
- In the header, you set "Platforms" to php, this should be python
- I suggest you pint to https://github.com/Azure/azure-iot-sdks/blob/master/doc/setup_iothub.md for the instructions on how to create the IoT Hub, that way you don't have to maintain this if/when this changes.

**Comment by dalechen** [comment]
Thanks for the suggestions, I am oof now, I will make the changes on Tuesday when I come back to the office.

-Dale Chen

**Comment by olivierbloch** [comment]
Hi @dalechen 
Any ETA on this one?
Thanks

I updated that article and links to https://azure.microsoft.com/documentation/articles/iot-hub-csharp-csharp-getstarted/#create-an-iot-hub.

**Comment by dalechen** [comment]
Thanks for tracking on this, the platform was set to Python from Php. For the second suggestion, I am confirming with the original author, I should be able to update it next Tuesday when I get to the offoce.

-Dale Chen
发件人: Olivier Bloch [mailto:notifications@github.com]
发送时间: Monday, June 6, 2016 2:05 PM
收件人: Azure-Samples/iot-hub-python-get-started iot-hub-python-get-started@noreply.github.com
抄送: Dale Chen Chen.Daoquan@microsoft.com; Mention mention@noreply.github.com
主题: Re: [Azure-Samples/iot-hub-python-get-started] Readme udpates needed (#1)

Hi @dalechenhttps://github.com/dalechen
Any ETA on this one?
Thanks

**Comment by olivierbloch** [comment]
Hi @dalechen 
Can this one be closed?
